### ISSUE TITLE
Lat, Long for to address

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-directions#17]
Hi Eddy, 

Can I pass Lat and Long to the to: array instead of an address, or in conjunction with an address? How would I do this and which one will be used as default?

**Comment by EddyVerbruggen** [comment]
Hi!

Yes, look at the usages of [this function](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/b23f677321d56b8d39e37738a1ed04e6df554d3a/app/mapping/mapping.component.ts#L177-L190) in my plugins demo app.

It's an array because you can have multiple waypoints, so there's no default. You can even mix lat/lng and address in one Array (for multiple waypoints).

**Comment by delanick** [comment]
@EddyVerbruggen Thanks bud, appreciated! That's an awesome plugin BTW!
